services:

  nginx:
    image: nginx:latest
    container_name: nginx-service
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/src:/var/www/html
    depends_on:
      - app
    networks:
      - app-network

  app:
    build: ./app
    container_name: php-service
    volumes:
      - ./app/src:/var/www/html
    networks:
      - app-network

networks:
  app-network:
